version: '3.9'
services:
  php:
    build:
      context: .
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/