version: '3.9'
services:
  php:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    depends_on:
      database:
        condition: service_healthy
  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
  database:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    ports:
      - '3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 20s
      retries: 20


